### ISSUE TITLE
[task]: create generic pod template

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/avalanchego#6]
It will be very helpful for testing to have a generic pod spec that can be adjusted for our usecase. Basic example.
```
apiVersion: v1
kind: Pod
metadata:
  name: tokenvm
  image: ${IMAGE}
  env:
    - name: "FOO"
      value: "BAR"
  hostNetwork: true
  resources:
    requests:
      memory: 600Mi
      cpu: 300m
```

**Comment by aaronbuchwald** [comment]
Here's the spec for the Subnet-EVM container pushed to @exdx 's Dockerhub:

```
apiVersion: v1
kind: Pod
metadata:
  name: subnet-evm
spec:
  containers:
  - name: subnet-evm
    image: dansoveravax/subnet-evm-container:v0.0.1-arm64
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 600Mi
        cpu: 300m
    env:
      - name: "AVALANCHE_VM_RUNTIME_ENGINE_ADDR"
        value: "127.0.0.1:9650"
```

**Comment by aaronbuchwald** [comment]
How would we make this generic and inject environment variables for `AVALANCHE_VM_RUNTIME_ENGINE_ADDR` and the image name?

I think this works hardcoded for the purposes of the demo

**Comment by exdx** [comment]
Updated version:
```
apiVersion: v1
kind: Pod
metadata:
  name: subnet-evm
spec:
  containers:
  - name: subnet-evm
    image: dansoveravax/subnet-evm-container:v0.0.1-arm64
    ports:
    - containerPort: 9000
    resources:
      requests:
        memory: 600Mi
        cpu: 300m
    env:
      - name: "AVALANCHE_VM_RUNTIME_ENGINE_ADDR"
        value: "127.0.0.1:9650"
```

**Comment by hexfusion** [comment]
ensure hostNetwork  is true or it wont be able to communicate with avalanchego
```
apiVersion: v1
kind: Pod
metadata:
  name: subnet-evm
spec:
  hostNetwork: true
  containers:
  - name: subnet-evm
    image: dansoveravax/subnet-evm-container:v0.0.1-arm64
    ports:
    - containerPort: 9000
    resources:
      requests:
        memory: 600Mi
        cpu: 300m
```
